// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package application

import (
	"context"
	"fmt"
	"github.com/Nexters/myply/application/controller"
	"github.com/Nexters/myply/domain/memos"
	"github.com/Nexters/myply/infrastructure/configs"
	"github.com/Nexters/myply/infrastructure/logger"
	"github.com/Nexters/myply/infrastructure/persistence"
	"github.com/Nexters/myply/infrastructure/persistence/db"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/swagger"
	"github.com/google/uuid"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.uber.org/zap"
	"time"
)

import (
	_ "github.com/Nexters/myply/docs"
)

// Injectors from server.go:

func New() (*fiber.App, error) {
	config, err := configs.NewConfig()
	if err != nil {
		return nil, err
	}
	sugaredLogger, err := logger.NewLogger(config)
	if err != nil {
		return nil, err
	}
	mongoInstance, err := db.NewMongoDB(config)
	if err != nil {
		return nil, err
	}
	repository := persistence.NewMemoRepository(mongoInstance)
	service := memos.NewMemoService(repository)
	memoController := controller.NewMemoController(service)
	app := NewServer(config, sugaredLogger, mongoInstance, memoController)
	return app, nil
}

// server.go:

// @title MYPLY SERVER
// @version 1.0
// @description This is a sample swagger for Fiber
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email minkj1992@gmail.com
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:8080
// @BasePath /
func NewServer(
	config *configs.Config, logger2 *zap.SugaredLogger,
	mongo *db.MongoInstance,
	mc *controller.MemoController,
) *fiber.App {

	collection := mongo.Db.Collection("members")
	member := persistence.Member{
		ID:      uuid.NewString(),
		Name:    "leoo",
		MemoIDs: []primitive.ObjectID{},
	}

	insertionResult, _ := collection.InsertOne(context.Background(), member)
	logger2.
		Infof("Instance\n%+v", insertionResult)

	collection = mongo.Db.Collection("memos")
	memoId := primitive.NewObjectID()
	fmt.Printf("objectId: %s", memoId)
	fmt.Printf("objectId in string: %s", memoId.String())
	memo2 := persistence.MemoData{
		ID:             primitive.NewObjectID(),
		DeviceToken:    "",
		YoutubeVideoId: "",
		Body:           "",
		TagIds:         nil,
		CreatedAt: primitive.Timestamp{
			T: uint32(time.Now().Unix()),
			I: 0,
		},
		UpdatedAt: primitive.Timestamp{
			T: uint32(time.Now().Unix()),
			I: 0,
		},
	}
	insertionResult, _ = collection.InsertOne(context.Background(), memo2)
	logger2.
		Infof("Instance\n%+v", insertionResult)

	findResult := collection.FindOne(context.Background(), bson.M{"_id": memoId})
	logger2.
		Infof("Instance\n%+v", findResult)
	logger2.
		Infof("Configuration settings\n%+v", config)
	app := fiber.New()

	app.Get("/swagger/*", swagger.HandlerDefault)
	app.Get("/swagger/*", swagger.New(swagger.Config{
		URL:         "http://example.com/doc.json",
		DeepLinking: false,

		DocExpansion: "none",
	}))
	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString(fmt.Sprintf("[%s] Hello, myply ✈️", config.Phase))
	})
	app.Get("/v1/memos/:id", (*mc).GetMemo)
	app.Post("/v1/memos", (*mc).AddMemo)

	return app
}
